[2024-03-01 11:13:37,913] INFO in base: Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2024-03-01 11:13:37,914] INFO in base: Added job "my_scheduled_job" to job store "default"
[2024-03-01 11:13:37,914] INFO in base: Scheduler started
[2024-03-01 11:13:37,915] DEBUG in base: Looking for jobs to run
[2024-03-01 11:13:37,918] DEBUG in base: Next wakeup is due at 2024-03-01 11:18:37.913164+03:00 (in 299.994988 seconds)
[2024-03-01 11:13:45,373] INFO in _internal:  * Restarting with stat
[2024-03-01 11:13:46,909] INFO in base: Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2024-03-01 11:13:46,909] INFO in base: Added job "my_scheduled_job" to job store "default"
[2024-03-01 11:13:46,910] INFO in base: Scheduler started
[2024-03-01 11:13:46,911] DEBUG in base: Looking for jobs to run
[2024-03-01 11:13:46,914] DEBUG in base: Next wakeup is due at 2024-03-01 11:18:46.909242+03:00 (in 299.995003 seconds)
[2024-03-01 11:13:48,340] WARNING in _internal:  * Debugger is active!
[2024-03-01 11:13:48,348] INFO in _internal:  * Debugger PIN: 125-542-277
[2024-03-01 11:13:48,510] INFO in _internal:  * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
[2024-03-01 11:18:37,919] DEBUG in base: Looking for jobs to run
[2024-03-01 11:18:37,922] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:23:37 +03)" (scheduled at 2024-03-01 11:18:37.913164+03:00)
[2024-03-01 11:18:37,922] DEBUG in base: Next wakeup is due at 2024-03-01 11:23:37.913164+03:00 (in 299.992370 seconds)
[2024-03-01 11:18:37,936] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:23:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:18:46,911] DEBUG in base: Looking for jobs to run
[2024-03-01 11:18:46,912] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:23:46 +03)" (scheduled at 2024-03-01 11:18:46.909242+03:00)
[2024-03-01 11:18:46,912] DEBUG in base: Next wakeup is due at 2024-03-01 11:23:46.909242+03:00 (in 299.997588 seconds)
[2024-03-01 11:18:46,918] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:23:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:23:37,925] DEBUG in base: Looking for jobs to run
[2024-03-01 11:23:37,925] DEBUG in base: Next wakeup is due at 2024-03-01 11:28:37.913164+03:00 (in 299.987780 seconds)
[2024-03-01 11:23:37,925] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:28:37 +03)" (scheduled at 2024-03-01 11:23:37.913164+03:00)
[2024-03-01 11:23:37,929] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:28:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:23:46,924] DEBUG in base: Looking for jobs to run
[2024-03-01 11:23:46,925] DEBUG in base: Next wakeup is due at 2024-03-01 11:28:46.909242+03:00 (in 299.984166 seconds)
[2024-03-01 11:23:46,925] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:28:46 +03)" (scheduled at 2024-03-01 11:23:46.909242+03:00)
[2024-03-01 11:23:46,927] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:28:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:28:37,918] DEBUG in base: Looking for jobs to run
[2024-03-01 11:28:37,920] DEBUG in base: Next wakeup is due at 2024-03-01 11:33:37.913164+03:00 (in 299.993375 seconds)
[2024-03-01 11:28:37,921] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:33:37 +03)" (scheduled at 2024-03-01 11:28:37.913164+03:00)
[2024-03-01 11:28:37,925] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:33:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:28:46,919] DEBUG in base: Looking for jobs to run
[2024-03-01 11:28:46,927] DEBUG in base: Next wakeup is due at 2024-03-01 11:33:46.909242+03:00 (in 299.984073 seconds)
[2024-03-01 11:28:46,927] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:33:46 +03)" (scheduled at 2024-03-01 11:28:46.909242+03:00)
[2024-03-01 11:28:46,932] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:33:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:33:37,927] DEBUG in base: Looking for jobs to run
[2024-03-01 11:33:37,928] DEBUG in base: Next wakeup is due at 2024-03-01 11:38:37.913164+03:00 (in 299.985090 seconds)
[2024-03-01 11:33:37,928] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:38:37 +03)" (scheduled at 2024-03-01 11:33:37.913164+03:00)
[2024-03-01 11:33:37,929] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:38:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:33:46,919] DEBUG in base: Looking for jobs to run
[2024-03-01 11:33:46,920] DEBUG in base: Next wakeup is due at 2024-03-01 11:38:46.909242+03:00 (in 299.989915 seconds)
[2024-03-01 11:33:46,920] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:38:46 +03)" (scheduled at 2024-03-01 11:33:46.909242+03:00)
[2024-03-01 11:38:37,915] DEBUG in base: Looking for jobs to run
[2024-03-01 11:38:37,917] DEBUG in base: Next wakeup is due at 2024-03-01 11:43:37.913164+03:00 (in 299.996964 seconds)
