[2024-03-01 11:38:37,919] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:43:37 +03)" (scheduled at 2024-03-01 11:38:37.913164+03:00)
[2024-03-01 11:38:37,926] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:43:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:38:46,924] DEBUG in base: Looking for jobs to run
[2024-03-01 11:38:46,928] DEBUG in base: Next wakeup is due at 2024-03-01 11:43:46.909242+03:00 (in 299.982440 seconds)
[2024-03-01 11:38:46,928] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:43:46 +03)" (scheduled at 2024-03-01 11:38:46.909242+03:00)
[2024-03-01 11:38:46,930] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:43:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:43:37,926] DEBUG in base: Looking for jobs to run
[2024-03-01 11:43:37,928] DEBUG in base: Next wakeup is due at 2024-03-01 11:48:37.913164+03:00 (in 299.986038 seconds)
[2024-03-01 11:43:37,928] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:48:37 +03)" (scheduled at 2024-03-01 11:43:37.913164+03:00)
[2024-03-01 11:43:37,936] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:48:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:43:46,920] DEBUG in base: Looking for jobs to run
[2024-03-01 11:43:46,922] DEBUG in base: Next wakeup is due at 2024-03-01 11:48:46.909242+03:00 (in 299.987940 seconds)
[2024-03-01 11:43:46,922] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:48:46 +03)" (scheduled at 2024-03-01 11:43:46.909242+03:00)
[2024-03-01 11:43:46,931] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:48:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:48:37,920] DEBUG in base: Looking for jobs to run
[2024-03-01 11:48:37,922] DEBUG in base: Next wakeup is due at 2024-03-01 11:53:37.913164+03:00 (in 299.990701 seconds)
[2024-03-01 11:48:37,922] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:53:37 +03)" (scheduled at 2024-03-01 11:48:37.913164+03:00)
[2024-03-01 11:48:37,924] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:53:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:48:46,917] DEBUG in base: Looking for jobs to run
[2024-03-01 11:48:46,917] DEBUG in base: Next wakeup is due at 2024-03-01 11:53:46.909242+03:00 (in 299.991619 seconds)
[2024-03-01 11:48:46,917] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:53:46 +03)" (scheduled at 2024-03-01 11:48:46.909242+03:00)
[2024-03-01 11:48:46,919] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:53:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:53:37,926] DEBUG in base: Looking for jobs to run
[2024-03-01 11:53:37,927] DEBUG in base: Next wakeup is due at 2024-03-01 11:58:37.913164+03:00 (in 299.986303 seconds)
[2024-03-01 11:53:37,927] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:58:37 +03)" (scheduled at 2024-03-01 11:53:37.913164+03:00)
[2024-03-01 11:53:37,929] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:58:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:53:46,918] DEBUG in base: Looking for jobs to run
[2024-03-01 11:53:46,918] DEBUG in base: Next wakeup is due at 2024-03-01 11:58:46.909242+03:00 (in 299.991045 seconds)
[2024-03-01 11:53:46,919] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:58:46 +03)" (scheduled at 2024-03-01 11:53:46.909242+03:00)
[2024-03-01 11:53:46,921] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 11:58:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 11:58:37,922] DEBUG in base: Looking for jobs to run
[2024-03-01 11:58:37,925] DEBUG in base: Next wakeup is due at 2024-03-01 12:03:37.913164+03:00 (in 299.988144 seconds)
[2024-03-01 11:58:37,925] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:03:37 +03)" (scheduled at 2024-03-01 11:58:37.913164+03:00)
[2024-03-01 11:58:46,922] DEBUG in base: Looking for jobs to run
[2024-03-01 11:58:46,922] DEBUG in base: Next wakeup is due at 2024-03-01 12:03:46.909242+03:00 (in 299.986283 seconds)
[2024-03-01 11:58:46,922] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:03:46 +03)" (scheduled at 2024-03-01 11:58:46.909242+03:00)
