[2024-03-03 21:53:46,924] DEBUG in base: Looking for jobs to run
[2024-03-03 21:53:46,926] DEBUG in base: Next wakeup is due at 2024-03-03 21:58:46.909242+03:00 (in 299.982912 seconds)
[2024-03-03 21:53:46,926] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 21:58:46 +03)" (scheduled at 2024-03-03 21:53:46.909242+03:00)
[2024-03-03 21:53:46,928] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 21:58:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-03 21:58:37,954] DEBUG in base: Looking for jobs to run
[2024-03-03 21:58:37,955] DEBUG in base: Next wakeup is due at 2024-03-03 22:03:37.913164+03:00 (in 299.958155 seconds)
[2024-03-03 21:58:37,955] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:03:37 +03)" (scheduled at 2024-03-03 21:58:37.913164+03:00)
[2024-03-03 21:58:37,967] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:03:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-03 21:58:46,912] DEBUG in base: Looking for jobs to run
[2024-03-03 21:58:46,912] DEBUG in base: Next wakeup is due at 2024-03-03 22:03:46.909242+03:00 (in 299.996859 seconds)
[2024-03-03 21:58:46,912] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:03:46 +03)" (scheduled at 2024-03-03 21:58:46.909242+03:00)
[2024-03-03 21:58:46,914] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:03:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-03 22:03:37,927] DEBUG in base: Looking for jobs to run
[2024-03-03 22:03:37,927] DEBUG in base: Next wakeup is due at 2024-03-03 22:08:37.913164+03:00 (in 299.986030 seconds)
[2024-03-03 22:03:37,927] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:08:37 +03)" (scheduled at 2024-03-03 22:03:37.913164+03:00)
[2024-03-03 22:03:37,929] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:08:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-03 22:03:46,923] DEBUG in base: Looking for jobs to run
[2024-03-03 22:03:46,924] DEBUG in base: Next wakeup is due at 2024-03-03 22:08:46.909242+03:00 (in 299.985162 seconds)
[2024-03-03 22:03:46,924] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:08:46 +03)" (scheduled at 2024-03-03 22:03:46.909242+03:00)
[2024-03-03 22:03:46,928] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:08:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-03 22:08:37,924] DEBUG in base: Looking for jobs to run
[2024-03-03 22:08:37,928] DEBUG in base: Next wakeup is due at 2024-03-03 22:13:37.913164+03:00 (in 299.988213 seconds)
[2024-03-03 22:08:37,928] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:13:37 +03)" (scheduled at 2024-03-03 22:08:37.913164+03:00)
[2024-03-03 22:08:37,936] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:13:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-03 22:08:46,918] DEBUG in base: Looking for jobs to run
[2024-03-03 22:08:46,919] DEBUG in base: Next wakeup is due at 2024-03-03 22:13:46.909242+03:00 (in 299.989313 seconds)
[2024-03-03 22:08:46,919] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:13:46 +03)" (scheduled at 2024-03-03 22:08:46.909242+03:00)
[2024-03-03 22:08:46,923] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:13:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-03 22:13:37,935] DEBUG in base: Looking for jobs to run
[2024-03-03 22:13:37,935] DEBUG in base: Next wakeup is due at 2024-03-03 22:18:37.913164+03:00 (in 299.977508 seconds)
[2024-03-03 22:13:37,935] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:18:37 +03)" (scheduled at 2024-03-03 22:13:37.913164+03:00)
[2024-03-03 22:13:37,937] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:18:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-03 22:13:46,920] DEBUG in base: Looking for jobs to run
[2024-03-03 22:13:46,921] DEBUG in base: Next wakeup is due at 2024-03-03 22:18:46.909242+03:00 (in 299.988607 seconds)
[2024-03-03 22:13:46,921] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:18:46 +03)" (scheduled at 2024-03-03 22:13:46.909242+03:00)
[2024-03-03 22:18:37,918] DEBUG in base: Looking for jobs to run
[2024-03-03 22:18:37,919] DEBUG in base: Next wakeup is due at 2024-03-03 22:23:37.913164+03:00 (in 299.994269 seconds)
[2024-03-03 22:18:37,920] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-03 22:23:37 +03)" (scheduled at 2024-03-03 22:18:37.913164+03:00)
