[2024-03-01 12:48:37,937] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:53:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 12:48:46,915] DEBUG in base: Looking for jobs to run
[2024-03-01 12:48:46,919] DEBUG in base: Next wakeup is due at 2024-03-01 12:53:46.909242+03:00 (in 299.991397 seconds)
[2024-03-01 12:48:46,919] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:53:46 +03)" (scheduled at 2024-03-01 12:48:46.909242+03:00)
[2024-03-01 12:48:46,924] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:53:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 12:53:37,920] DEBUG in base: Looking for jobs to run
[2024-03-01 12:53:37,921] DEBUG in base: Next wakeup is due at 2024-03-01 12:58:37.913164+03:00 (in 299.992761 seconds)
[2024-03-01 12:53:37,921] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:58:37 +03)" (scheduled at 2024-03-01 12:53:37.913164+03:00)
[2024-03-01 12:53:37,923] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:58:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 12:53:46,921] DEBUG in base: Looking for jobs to run
[2024-03-01 12:53:46,921] DEBUG in base: Next wakeup is due at 2024-03-01 12:58:46.909242+03:00 (in 299.988081 seconds)
[2024-03-01 12:53:46,922] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:58:46 +03)" (scheduled at 2024-03-01 12:53:46.909242+03:00)
[2024-03-01 12:53:46,923] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 12:58:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 12:58:37,925] DEBUG in base: Looking for jobs to run
[2024-03-01 12:58:37,926] DEBUG in base: Next wakeup is due at 2024-03-01 13:03:37.913164+03:00 (in 299.987205 seconds)
[2024-03-01 12:58:37,926] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:03:37 +03)" (scheduled at 2024-03-01 12:58:37.913164+03:00)
[2024-03-01 12:58:37,927] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:03:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 12:58:46,911] DEBUG in base: Looking for jobs to run
[2024-03-01 12:58:46,913] DEBUG in base: Next wakeup is due at 2024-03-01 13:03:46.909242+03:00 (in 299.996744 seconds)
[2024-03-01 12:58:46,913] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:03:46 +03)" (scheduled at 2024-03-01 12:58:46.909242+03:00)
[2024-03-01 12:58:46,915] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:03:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 13:03:37,925] DEBUG in base: Looking for jobs to run
[2024-03-01 13:03:37,925] DEBUG in base: Next wakeup is due at 2024-03-01 13:08:37.913164+03:00 (in 299.987450 seconds)
[2024-03-01 13:03:37,925] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:08:37 +03)" (scheduled at 2024-03-01 13:03:37.913164+03:00)
[2024-03-01 13:03:37,928] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:08:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 13:03:46,921] DEBUG in base: Looking for jobs to run
[2024-03-01 13:03:46,922] DEBUG in base: Next wakeup is due at 2024-03-01 13:08:46.909242+03:00 (in 299.986363 seconds)
[2024-03-01 13:03:46,922] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:08:46 +03)" (scheduled at 2024-03-01 13:03:46.909242+03:00)
[2024-03-01 13:03:46,926] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:08:46 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
[2024-03-01 13:08:37,929] DEBUG in base: Looking for jobs to run
[2024-03-01 13:08:37,929] DEBUG in base: Next wakeup is due at 2024-03-01 13:13:37.913164+03:00 (in 299.983193 seconds)
[2024-03-01 13:08:37,930] INFO in base: Running job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:13:37 +03)" (scheduled at 2024-03-01 13:08:37.913164+03:00)
[2024-03-01 13:08:37,931] ERROR in base: Job "my_scheduled_job (trigger: interval[0:05:00], next run at: 2024-03-01 13:13:37 +03)" raised an exception
Traceback (most recent call last):
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\__init__.py", line 102, in my_scheduled_job
    feed = obj.get_feed()
           ^^^^^^^^^^^^^^
  File "G:\ITWEDO\Projet\Telma\moov-web\env\Lib\site-packages\moov\etl\afp.py", line 38, in get_feed
    with self.source as source:
TypeError: 'NoneType' object does not support the context manager protocol
